apiVersion: v1
kind: Secret
metadata:
  name: my-eks-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: my-eks-prod
  # 1. PASTE YOUR AWS EKS URL HERE
  server: https://B62063D086EFEE285F3C98454BF6DA64.gr7.us-east-1.eks.amazonaws.com
  config: |
    {
      
      "bearerToken": "XXXXXXXXXXXXiJSUzI1NiIsImtpZCI6IjVWakhIQmR0ekd4aE44VTk2bGtfT0FzbkZiWjRNZEJTYkg0YjBmNWY0QlkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcmdvY2QtbWFuYWdlci10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QtbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZjNzY4NGYzLTQyZjUtNDljZi04YWFjLWQ2Yjk3NGM3MTE3ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphcmdvY2QtbWFuYWdlciJ9.SbiXtK4PlcLNGkGyrJC8wfXMYkwyiCiIEdD0SFpqr_5fLNIVXK1L1dJAEKw51aKFtWZlDCytBpAf0-kvw0Xbs02TnOKzXJWBXCaLbt2DlzpryTtppfKTF_hyc6n1F5A-_HedqV5YJNhcltRGKwjgh2W-ltgKKULaudaiUYIctMOjPdMtH2Ui0zKpPtd5ekSCXt7IC3DL6S8OfbR8Y0z6y_LLIXEN_-O9n_ih4XmAF8KKN-conuUh_GbSyE3qu9e7Kiqc-t1RDATGyLGbMnwLSMRW8EInbrCz6QloM0hEsFkV6XRLTbQg_BvcDVTS0L_SBxpXPN7W5LE3aTsD8PA6mw",
      "tlsClientConfig": {
        "insecure": true
      }
    }

---

# 1. Create the ServiceAccount
kubectl create sa argocd-manager -n kube-system

# 2. Give it Admin permissions
kubectl create clusterrolebinding argocd-manager-role \
  --clusterrole=cluster-admin \
  --serviceaccount=kube-system:argocd-manager

# 3. Create the Token Secret (Required for K8s 1.24+)
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: argocd-manager-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: argocd-manager
type: kubernetes.io/service-account-token
EOF

kubectl -n kube-system get secret argocd-manager-token -o jsonpath="{.data.token}" | base64 -d
# COPY THIS LONG STRING

kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'
# COPY THIS URL (e.g., https://A1B2C3...gr7.us-east-1.eks.amazonaws.com)