apiVersion: apps/v1
kind: Deployment  
metadata:
  name: otel-collector
  namespace: default
  labels:
    app: otel-collector
spec:
  replicas: 1       # <--- Added Replicas
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      # 1. Privileged is still required on EKS to read host logs
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        securityContext:
          privileged: true
          runAsUser: 0
        
        command:
        - /otelcol-contrib
        - --config=/conf/otel-collector-config.yaml
        
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 13133
          name: health
        
        volumeMounts:
        - name: otel-collector-config
          mountPath: /conf
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true


        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 60
          periodSeconds: 5

      volumes:
      - name: otel-collector-config
        configMap:
          name: otel-collector-config
          items:
          - key: otel-collector-config.yaml
            path: otel-collector-config.yaml
      - name: varlogpods
        hostPath:
          path: /var/log/pods

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/*_otel-collector_*/*/*.log
        start_at: end
        include_file_path: true
        include_file_name: false
        operators:
          - type: json_parser
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'

    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
      
      resource:
        attributes:
          # 3. CHANGED: Update tags for EKS
          - key: deployment.environment
            value: "production-eks"  # <--- Update this!
            action: upsert
          - key: k8s.cluster.name
            value: "my-aws-cluster"  # <--- Update this!
            action: upsert

    exporters:
      datadog/exporter:
        api:
          site: "datadoghq.com"
          key: ODNkZThhZmJjNTM4NTUzZTYzY2I1OWI1NGIzNjg2NzE=  # <--- Update this!
        traces:
          span_name_as_resource_name: true
        logs:
          endpoint: https://http-intake.logs.datadoghq.com

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [datadog/exporter]
        logs:
          receivers: [filelog]
          processors: [resource, batch]
          exporters: [datadog/exporter]


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.12.0
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    # 1. Tell AWS to provision a Network Load Balancer (Faster/Cheaper than Classic)
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    
    # 2. (Optional) Ensure the Load Balancer is public (Internet-facing)
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    
    # 3. (Optional) If you want to use the AWS Load Balancer Controller (if installed)
    # service.beta.kubernetes.io/aws-load-balancer-type: external
    # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  
  # 4. CHANGE THIS FROM NodePort TO LoadBalancer
  type: LoadBalancer